# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ois', '0005_semesteruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkuser',
            name='group_work',
        ),
        migrations.AddField(
            model_name='notification',
            name='topic',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homeworkuser',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homeworkuser',
            name='mark',
            field=models.IntegerField(blank=True),
        ),
    ]
