# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ois', '0006_auto_20160510_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkuser',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='homeworkuser',
            name='mark',
            field=models.IntegerField(null=True),
        ),
    ]
