# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ois', '0007_auto_20160510_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homeworkuser',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homeworkuser',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
