# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='slug',
            field=models.CharField(default='cat', max_length=60),
        ),
    ]
